GAME_DISPLAY = (900, 600)
IMAGE_NAME_SEPARATOR = '_'
FPS = 30
DISPLAY_W, DISPLAY_H = GAME_DISPLAY

MAP_ITEM_W, MAP_ITEM_H = (32, 32)
MAP_SPRITESHEET_BIT_STR = '32'
MAP_SPRITESHEET_BIT_INT = 32

MAPS_FOLDER = 'resources/maps'
IMAGES_FOLDER = 'resources/images'
START_MAP_FOLDER = 'start_map'

